version: '3'
services:
  ldap:
    image: jenkinsciinfra/mock-ldap:latest
    ports:
        - 636:636
        - 389:389

  fake:
    build: .
    image: accountapp:latest
    depends_on:
      - ldap
    env_file: env.sandbox
    ports:
      - '8080:8080'

  local:
    build: .
    image: accountapp:latest
    env_file: .env
    network_mode: host
    ports:
      - '8080:8080'
