version: '3'
services:
  run:
    build: .
    image: accountapp:latest
    env_file: .env
    network_mode: host
    ports:
      - '8080:8080'

  shell:
    build: .
    image: accountapp:latest
    env_file: .env
    entrypoint: /bin/sh
    network_mode: host

  ldap:
    image: jenkins-infra/mock-ldap:latest
    ports:
      - 636:636
