version: '3'
services:
  run:
    image: jenkinsciinfra/account-app:49-build803587
    env_file: .env
    ports:
      - 8080:8080
    links:
      - ldap

  ldap:
    image: jenkinsciinfra/mock-ldap:latest
    ports:
      - 636:636
      - 389:389

  ruby:
    image: ruby:2.3
    user: $UID
    ports:
      - 4242:4242
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - $PWD/build/phantomjs:/phantomjs
    environment:
      PATH: "/phantomjs/bin:$PATH"
      LANG: 'C.UTF-8'
      GEM_HOME: "${PWD}/vendor/gems"
      BUNDLE_PATH: "${PWD}/vendor/gems"
      BUNDLE_APP_CONFIG: "${PWD}/vendor/gems/.bundle"
      BUNDLE_DISABLE_SHARED_GEMS: 'true'
    links:
      - run
