#!/usr/bin/env bash

if [ ! -z ${LISTEN+x} ]; then
    ADDITIONAL_ARGS="-p 4242:4242"
fi;

exec docker run --rm \
    ${ADDITIONAL_ARGS} \
    -u $(id -u):$(id -g) \
    -e LANG=C.UTF-8 \
    -e HOME="${PWD}" \
    -e PATH="/phantomjs/bin:$PATH" \
    -e GEM_HOME="${PWD}/vendor/gems" \
    -e BUNDLE_PATH="${PWD}/vendor/gems" \
    -e BUNDLE_APP_CONFIG="${PWD}/vendor/gems/.bundle" \
    -e BUNDLE_DISABLE_SHARED_GEMS=true \
    -v "${PWD}/phantomjs-2.1.1-linux-x86_64/":/phantomjs:delegated \
    -v "${PWD}":"${PWD}":delegated \
    -w "${PWD}" \
    ruby:2.3 $@
